### ISSUE TITLE
1.20.1服務器正常開啟，客戶端連接失敗

### ISSUE THREAD

**Issue by mss0517** [KenRouKoro/WAC#1]
提示lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.util.NoSuchElementException: No value present
單人世界也可以正常開啟，只有連線時會發生此問題。

**Comment by mss0517** [comment]
log：
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:143) ~[?:?]
	at net.minecraft.class_6895.method_40350(class_6895.java:35) ~[server-intermediary.jar:?]
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.Codec$2.encode(Codec.java:76) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.encode(KeyDispatchCodec.java:98) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.codecs.BaseMapCodec.encode(BaseMapCodec.java:52) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.codecs.UnboundedMapCodec.encode(UnboundedMapCodec.java:43) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.codecs.UnboundedMapCodec.encode(UnboundedMapCodec.java:17) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.Codec$2.encode(Codec.java:76) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_2540.method_29172(class_2540.java:147) ~[server-intermediary.jar:?]
	at net.minecraft.class_2678.method_11052(class_2678.java:77) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Iron237** [comment]
同样的问题+1

**Comment by AoscaRyan** [comment]
同样的问题，链接出错时提示：Internal Exception: io.netty.handler.codec.EncoderException: java.util.NoSuchElementException: No value present
